const API_MESSAGE_MAP = {
  'Not authorized, no token': 'api.not_authorized',
  'Not authorized, token failed': 'api.token_failed',
  'Staff not found': 'api.staff_not_found',
  'User not found': 'api.user_not_found',
  'Access denied. Admin only.': 'api.admin_only',
  'Access denied.': 'api.access_denied',
  'Access denied': 'api.access_denied',
  'Your account has been suspended.': 'api.account_suspended',
  'Account not approved yet. Contact admin.': 'api.account_not_approved',
  'Your account has been rejected. Contact support for more information.': 'api.account_rejected',
  'Your account has been rejected. Contact support.': 'api.account_rejected',
  'Your account has been suspended. Contact support.': 'api.account_suspended',
  'Your account is pending approval. Please complete WhatsApp verification and wait for admin approval.': 'api.account_pending',
  'Your account is pending admin approval. Please wait for approval.': 'api.account_pending',
  'Name, email and password are required': 'api.name_email_password_required',
  'Email already registered': 'api.email_registered',
  'Email and password are required': 'api.email_password_required',
  'Invalid email or password': 'api.invalid_credentials',
  'Email and password required': 'api.email_password_required',
  'Invalid credentials': 'api.invalid_email_password',
  'Account is inactive. Contact your manager.': 'api.staff_inactive',
  'Staff only': 'api.staff_only',
  'Name, email, and password are required': 'api.name_email_password_required',
  'Password is required': 'api.password_required',
  'Account suspended': 'api.account_suspended',
  'Password must be at least 6 characters': 'api.password_too_short',
  'Name is required': 'api.name_required',
  'Email is required': 'api.email_required',
  'Invalid email format': 'api.invalid_email',
  'Email already in use': 'api.email_in_use',
  'Cannot suspend super admin': 'api.cannot_suspend_super_admin',
  'Can only impersonate tenants': 'api.can_only_impersonate_tenants',
  'Cannot impersonate unapproved tenants': 'api.cannot_impersonate_unapproved',
  'Sub-admin not found': 'api.sub_admin_not_found',
  'Phone number and message are required': 'api.phone_message_required',
  'businessId, name, and phone are required': 'api.business_info_required',
  'Business ID already exists': 'api.business_id_exists',
  'Business not found': 'api.business_not_found',
  'Message is required': 'api.message_required',
  'No contacts found to broadcast to': 'api.no_contacts_broadcast',
  'Customer name and items are required': 'api.customer_items_required',
  'Each item needs a productId and quantity >= 1': 'api.item_needs_product',
  'Order not found': 'api.order_not_found',
  'Order has no customer phone number': 'api.order_no_phone',
  'WhatsApp connection not available': 'api.wa_not_available',
  'Failed to send receipt': 'api.receipt_send_failed',
  'Invalid type': 'api.invalid_type',
  'Item not found': 'api.item_not_found',
  'Notification not found': 'api.notification_not_found',
  'Product name, quantity, and cost are required': 'api.purchase_info_required',
  'Purchase not found': 'api.purchase_not_found',
  'Description and amount are required': 'api.expense_info_required',
  'Expense not found': 'api.expense_not_found',
  'Customer name and amount are required': 'api.debt_info_required',
  'Debt not found': 'api.debt_not_found',
  'Valid payment amount required': 'api.valid_payment_required',
  'name and price are required': 'api.product_info_required',
  'Product not found': 'api.product_not_found',
  'CSV file is required': 'api.csv_required',
  'Quantity must be > 0': 'api.quantity_invalid',
  'Phone number is required': 'api.phone_required',
  'Invalid phone number': 'api.invalid_phone',
  'Contact not found': 'api.contact_not_found',
  'Only JPG, PNG, and WEBP images are allowed': 'api.image_format_invalid',
  'Only CSV files are allowed': 'api.csv_only',
  'Cannot approve admin accounts': 'api.cannot_approve_admin',
  'Cannot reject admin accounts': 'api.cannot_reject_admin',
  'User not found in recycle bin': 'api.not_in_recycle_bin',
  'Order not found in recycle bin': 'api.not_in_recycle_bin',
  'Notification not found in recycle bin': 'api.not_in_recycle_bin',
  'Product not found in recycle bin': 'api.not_in_recycle_bin',
  'Contact not found in recycle bin': 'api.not_in_recycle_bin',
  'Missing permission: view_tenants': 'api.missing_tenant_permission',
  'Message sent successfully': 'api.success_message_sent',
  'Already connected': 'api.already_connected',
  'Connection in progress. Scan the QR code.': 'api.connection_in_progress',
  'QR code generated. Scan with WhatsApp > Linked Devices.': 'api.qr_generated',
  'WhatsApp disconnected': 'api.wa_disconnected',
  'Password updated': 'api.password_updated',
  'Staff deleted': 'api.staff_deleted',
  'Item restored': 'api.item_restored',
  'Item permanently deleted': 'api.item_permanently_deleted',
  'Product moved to recycle bin': 'api.product_recycled',
  'Product restored': 'api.product_restored',
  'Product permanently deleted': 'api.product_permanently_deleted',
  'Manual order created and marked as paid': 'api.order_created',
  'Order approved, payment requested, and customer notified': 'api.order_approved',
  'Order rejected and customer notified': 'api.order_rejected',
  'Payment confirmed, receipt sent, and customer notified': 'api.payment_confirmed',
  'Delivery confirmed and customer notified': 'api.delivery_confirmed',
  'Order moved to recycle bin': 'api.order_recycled',
  'Order restored': 'api.order_restored',
  'Order permanently deleted': 'api.order_permanently_deleted',
  'All notifications moved to recycle bin': 'api.notifications_recycled',
  'Notification moved to recycle bin': 'api.notification_recycled',
  'Notification restored': 'api.notification_restored',
  'Notification permanently deleted': 'api.notification_permanently_deleted',
  'Expense deleted': 'api.expense_deleted',
  'Debt deleted': 'api.debt_deleted',
  'Reminder sent via WhatsApp': 'api.reminder_sent',
  'Contact already exists': 'api.contact_exists',
  'Contact added successfully': 'api.contact_added',
  'Contact moved to recycle bin': 'api.contact_recycled',
  'Contact restored': 'api.contact_restored',
  'Contact permanently deleted': 'api.contact_permanently_deleted',
  'Registration successful! Please login and connect your WhatsApp number. After scanning, your details will be sent to the admin for approval.': 'api.registration_success',
  'Please connect your WhatsApp to complete registration.': 'api.wa_not_available',
  'User moved to recycle bin': 'api.user_recycled',
  'User restored': 'api.user_restored',
  'User permanently deleted': 'api.user_permanently_deleted',
  'Sub-admin updated': 'api.sub_admin_updated',
  'Receipt sent to customer': 'api.receipt_sent',
};

export function translateApiMessage(message, t) {
  if (!message) return t ? t('common.error') : 'Error';
  const key = API_MESSAGE_MAP[message];
  if (key && t) return t(key);
  return message;
}

export default translateApiMessage;
